import { describe, expect, it } from 'vitest';
import html from '../../designs/ghostterm-ui-concepts.html?raw';
import workspaceHtml from '../../designs/habitat-grid-workspace.html?raw';
import toolsHtml from '../../designs/habitat-grid-tools.html?raw';
import progressHtml from '../../designs/habitat-grid-progress.html?raw';
import progressInteractionsHtml from '../../designs/habitat-grid-progress-interactions.html?raw';
import atlasIconPreviewHtml from '../../designs/atlas-icon-preview.html?raw';

describe('GhostTerm 设计稿交付物', () => {
  it('应存在包含三套高保真方案的静态设计页', () => {
    expect(html).toContain('Atlas Chamber');
    expect(html).toContain('Loom Engine');
    expect(html).toContain('Habitat Grid');
    expect(html).toContain('Workspace');
    expect(html).toContain('Tools');
    expect(html).toContain('Settings');
  });

  it('应存在 Habitat Grid 三个独立功能设计稿页面', () => {
    expect(workspaceHtml).toContain('Habitat Grid / Workspace');
    expect(workspaceHtml).toContain('当前项目');
    expect(workspaceHtml).toContain('项目目录');
    expect(workspaceHtml).toContain('文件入口');
    expect(workspaceHtml).toContain('代码工作区');
    expect(workspaceHtml).toContain('终端任务');
    expect(workspaceHtml).toContain('工作状态');
    expect(toolsHtml).toContain('Habitat Grid / Tools');
    expect(toolsHtml).toContain('Forensic Tool Lab');
    expect(progressHtml).toContain('Habitat Grid / Progress');
    expect(progressHtml).toContain('GhostTerm · 进度模块');
    expect(progressHtml).toContain('看板视图');
    expect(progressHtml).toContain('列表视图');
    expect(progressHtml).toContain('Gantt视图');
    expect(progressHtml).toContain('S1');
    expect(progressHtml).toContain('S6');
    expect(progressHtml).toContain('洽谈中');
    expect(progressHtml).toContain('报价中');
    expect(progressHtml).toContain('开发中');
    expect(progressHtml).toContain('待验收');
    expect(progressHtml).toContain('已交付');
    expect(progressHtml).toContain('已收款');
    expect(progressHtml).not.toContain('state-mark');
    expect(progressInteractionsHtml).toContain('Habitat Grid / Progress Interactions');
    expect(progressInteractionsHtml).toContain('项目详情页 / ProjectDetailPage');
    expect(progressInteractionsHtml).toContain('新建项目 / 事件流转 / 报价变更 / 收款登记');
    expect(progressInteractionsHtml).toContain('通知中心 / NotificationsCenterView');
    expect(progressInteractionsHtml).toContain('收益结算页 / EarningsView');
    expect(progressInteractionsHtml).toContain('反馈、论文版本与文件区');
    expect(progressInteractionsHtml).toContain('ProjectCreateDialog');
    expect(progressInteractionsHtml).toContain('EventTriggerDialog');
    expect(progressInteractionsHtml).toContain('QuoteChangeDialog');
    expect(progressInteractionsHtml).toContain('PaymentDialog');
    expect(progressInteractionsHtml).toContain('内部面板独立滚动');
    expect(progressInteractionsHtml).toContain('同 habitat-grid-progress.html 视觉系统');
    expect(atlasIconPreviewHtml).toContain('Atlas Control Brandkit Preview');
    expect(atlasIconPreviewHtml).toContain('Atlas Control Mark / Brandkit Skill Trial');
    expect(atlasIconPreviewHtml).toContain('atlas-control-brandkit-board.png');
    expect(atlasIconPreviewHtml).toContain('atlas-control-mark.png');
    expect(atlasIconPreviewHtml).toContain('Leonxlnx/taste-skill');
    expect(atlasIconPreviewHtml).toContain('Control core / 项目运行总控');
    expect(atlasIconPreviewHtml).not.toContain('atlas-icon.svg');
    expect(atlasIconPreviewHtml).not.toContain('Atlas Navigator Mascot');
    expect(atlasIconPreviewHtml).not.toContain('Atlas Paperflow Mark Preview');
    expect(atlasIconPreviewHtml).not.toContain('Atlas Folio Map Mark');
    expect(atlasIconPreviewHtml).toContain('单图标候选 / Atlas Control Mark');
  });
});
