// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AuthGetMe implements authGetMe operation.
	//
	// 获取当前登录用户.
	//
	// GET /api/auth/me
	AuthGetMe(ctx context.Context) (AuthGetMeRes, error)
	// AuthLogin implements authLogin operation.
	//
	// 登录获取 access + refresh token.
	//
	// POST /api/auth/login
	AuthLogin(ctx context.Context, req *AuthLoginRequest) (AuthLoginRes, error)
	// AuthLogout implements authLogout operation.
	//
	// 登出（递增 token_version 使所有 token 失效）.
	//
	// POST /api/auth/logout
	AuthLogout(ctx context.Context) (AuthLogoutRes, error)
	// AuthRefresh implements authRefresh operation.
	//
	// 用 refresh token 换 access token.
	//
	// POST /api/auth/refresh
	AuthRefresh(ctx context.Context, req *AuthRefreshRequest) (AuthRefreshRes, error)
	// DashboardGetRisks implements dashboardGetRisks operation.
	//
	// 风险总览（临近 deadline / 已超期 / 应收逾期），按 RBAC 过滤.
	//
	// GET /api/dashboard/risks
	DashboardGetRisks(ctx context.Context) (DashboardGetRisksRes, error)
	// FeedbacksUpdate implements feedbacksUpdate operation.
	//
	// 修改反馈状态（pending → done）.
	//
	// PATCH /api/feedbacks/{id}
	FeedbacksUpdate(ctx context.Context, req *FeedbackUpdateRequest, params FeedbacksUpdateParams) (FeedbacksUpdateRes, error)
	// FilesDownload implements filesDownload operation.
	//
	// 下载文件（流式）.
	//
	// GET /api/files/{id}
	FilesDownload(ctx context.Context, params FilesDownloadParams) (FilesDownloadRes, error)
	// FilesUpload implements filesUpload operation.
	//
	// 上传文件，返回文件元数据.
	//
	// POST /api/files
	FilesUpload(ctx context.Context, req *FilesUploadReq) (FilesUploadRes, error)
	// MeEarnings implements meEarnings operation.
	//
	// 当前用户收益视图（自动按 user_id 过滤）.
	//
	// GET /api/me/earnings
	MeEarnings(ctx context.Context) (*EarningsSummaryResponse, error)
	// NotificationsList implements notificationsList operation.
	//
	// 当前用户通知.
	//
	// GET /api/notifications
	NotificationsList(ctx context.Context, params NotificationsListParams) (*NotificationListResponse, error)
	// NotificationsMarkAllRead implements notificationsMarkAllRead operation.
	//
	// 全部标为已读.
	//
	// POST /api/notifications/read-all
	NotificationsMarkAllRead(ctx context.Context) error
	// NotificationsMarkRead implements notificationsMarkRead operation.
	//
	// 标记单条通知为已读.
	//
	// POST /api/notifications/{id}/read
	NotificationsMarkRead(ctx context.Context, params NotificationsMarkReadParams) (NotificationsMarkReadRes, error)
	// PermissionsList implements permissionsList operation.
	//
	// 列出所有权限.
	//
	// GET /api/permissions
	PermissionsList(ctx context.Context) (PermissionsListRes, error)
	// ProjectsCreate implements projectsCreate operation.
	//
	// 创建项目（默认进入 dealing 状态）.
	//
	// POST /api/projects
	ProjectsCreate(ctx context.Context, req *ProjectCreateRequest) (ProjectsCreateRes, error)
	// ProjectsCreateFeedback implements projectsCreateFeedback operation.
	//
	// POST /api/projects/{id}/feedbacks
	ProjectsCreateFeedback(ctx context.Context, req *FeedbackCreateRequest, params ProjectsCreateFeedbackParams) (ProjectsCreateFeedbackRes, error)
	// ProjectsCreatePayment implements projectsCreatePayment operation.
	//
	// 录入收款或开发结算.
	//
	// POST /api/projects/{id}/payments
	ProjectsCreatePayment(ctx context.Context, req *PaymentCreateRequest, params ProjectsCreatePaymentParams) (ProjectsCreatePaymentRes, error)
	// ProjectsCreateQuoteChange implements projectsCreateQuoteChange operation.
	//
	// 提交费用变更（追加 / 修改 / 售后）.
	//
	// POST /api/projects/{id}/quote-changes
	ProjectsCreateQuoteChange(ctx context.Context, req *QuoteChangeRequest, params ProjectsCreateQuoteChangeParams) (ProjectsCreateQuoteChangeRes, error)
	// ProjectsCreateThesisVersion implements projectsCreateThesisVersion operation.
	//
	// 上传论文新版（永不覆盖，version_no 自动递增）.
	//
	// POST /api/projects/{id}/thesis-versions
	ProjectsCreateThesisVersion(ctx context.Context, req *ThesisVersionCreateRequest, params ProjectsCreateThesisVersionParams) (ProjectsCreateThesisVersionRes, error)
	// ProjectsGet implements projectsGet operation.
	//
	// GET /api/projects/{id}
	ProjectsGet(ctx context.Context, params ProjectsGetParams) (ProjectsGetRes, error)
	// ProjectsList implements projectsList operation.
	//
	// 列出项目（按 RBAC 过滤）.
	//
	// GET /api/projects
	ProjectsList(ctx context.Context, params ProjectsListParams) (ProjectsListRes, error)
	// ProjectsListActivities implements projectsListActivities operation.
	//
	// 查询项目进度时间线（聚合 7 类事件，时间倒序）.
	//
	// GET /api/projects/{id}/activities
	ProjectsListActivities(ctx context.Context, params ProjectsListActivitiesParams) (ProjectsListActivitiesRes, error)
	// ProjectsListFeedbacks implements projectsListFeedbacks operation.
	//
	// GET /api/projects/{id}/feedbacks
	ProjectsListFeedbacks(ctx context.Context, params ProjectsListFeedbacksParams) (*FeedbackListResponse, error)
	// ProjectsListFiles implements projectsListFiles operation.
	//
	// 列出项目附件（sample_doc / source_code）.
	//
	// GET /api/projects/{id}/files
	ProjectsListFiles(ctx context.Context, params ProjectsListFilesParams) (*ProjectFileListResponse, error)
	// ProjectsListPayments implements projectsListPayments operation.
	//
	// GET /api/projects/{id}/payments
	ProjectsListPayments(ctx context.Context, params ProjectsListPaymentsParams) (*PaymentListResponse, error)
	// ProjectsListQuoteChanges implements projectsListQuoteChanges operation.
	//
	// GET /api/projects/{id}/quote-changes
	ProjectsListQuoteChanges(ctx context.Context, params ProjectsListQuoteChangesParams) (*QuoteChangeListResponse, error)
	// ProjectsListThesisVersions implements projectsListThesisVersions operation.
	//
	// GET /api/projects/{id}/thesis-versions
	ProjectsListThesisVersions(ctx context.Context, params ProjectsListThesisVersionsParams) (*ThesisVersionListResponse, error)
	// ProjectsStatusChanges implements projectsStatusChanges operation.
	//
	// 查询项目状态变更日志.
	//
	// GET /api/projects/{id}/status-changes
	ProjectsStatusChanges(ctx context.Context, params ProjectsStatusChangesParams) (ProjectsStatusChangesRes, error)
	// ProjectsTriggerEvent implements projectsTriggerEvent operation.
	//
	// 触发状态机事件.
	//
	// POST /api/projects/{id}/events
	ProjectsTriggerEvent(ctx context.Context, req *EventTriggerRequest, params ProjectsTriggerEventParams) (ProjectsTriggerEventRes, error)
	// ProjectsUpdate implements projectsUpdate operation.
	//
	// 修改项目基础字段（不含状态机）.
	//
	// PATCH /api/projects/{id}
	ProjectsUpdate(ctx context.Context, req *ProjectUpdateRequest, params ProjectsUpdateParams) (ProjectsUpdateRes, error)
	// RolesCreate implements rolesCreate operation.
	//
	// 创建角色（仅超管）.
	//
	// POST /api/roles
	RolesCreate(ctx context.Context, req *RoleCreateRequest) (RolesCreateRes, error)
	// RolesGetPermissions implements rolesGetPermissions operation.
	//
	// 查询某角色绑定的权限列表.
	//
	// GET /api/roles/{id}/permissions
	RolesGetPermissions(ctx context.Context, params RolesGetPermissionsParams) (RolesGetPermissionsRes, error)
	// RolesList implements rolesList operation.
	//
	// 列出所有角色.
	//
	// GET /api/roles
	RolesList(ctx context.Context) (RolesListRes, error)
	// RolesUpdatePermissions implements rolesUpdatePermissions operation.
	//
	// 替换某角色的权限绑定（仅超管，按 permissionIds 全量覆盖）.
	//
	// PATCH /api/roles/{id}/permissions
	RolesUpdatePermissions(ctx context.Context, req *RolePermissionUpdateRequest, params RolesUpdatePermissionsParams) (RolesUpdatePermissionsRes, error)
	// UsersCreate implements usersCreate operation.
	//
	// 创建用户（仅超管）.
	//
	// POST /api/users
	UsersCreate(ctx context.Context, req *UserCreateRequest) (UsersCreateRes, error)
	// UsersDelete implements usersDelete operation.
	//
	// 删除用户（仅超管，软删除：置 isActive=false 并失效 token_version）.
	//
	// DELETE /api/users/{id}
	UsersDelete(ctx context.Context, params UsersDeleteParams) (UsersDeleteRes, error)
	// UsersList implements usersList operation.
	//
	// 列出所有用户（仅超管）.
	//
	// GET /api/users
	UsersList(ctx context.Context) (UsersListRes, error)
	// UsersUpdate implements usersUpdate operation.
	//
	// 修改用户（仅超管）.
	//
	// PATCH /api/users/{id}
	UsersUpdate(ctx context.Context, req *UserUpdateRequest, params UsersUpdateParams) (UsersUpdateRes, error)
	// WsNotificationsConnect implements wsNotificationsConnect operation.
	//
	// WebSocket 升级端点（非 HTTP REST，仅 OpenAPI 描述）。
	// 协议：客户端 query 参数携带 ticket，服务端校验 ticket 后升级；
	// 消息帧 JSON：{ "type": "notification.new" | "ping" | "pong", "data": <payload> }。
	// ogen 不会为此生成 handler，由 router.go 直接注册 ws 处理器。.
	//
	// GET /api/ws/notifications
	WsNotificationsConnect(ctx context.Context, params WsNotificationsConnectParams) (WsNotificationsConnectRes, error)
	// WsTicketIssue implements wsTicketIssue operation.
	//
	// 签发 WebSocket 票据（30s 有效）.
	//
	// POST /api/ws/ticket
	WsTicketIssue(ctx context.Context) (*WSTicketResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
