// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthLogin implements authLogin operation.
//
// 登录获取 access + refresh token.
//
// POST /api/auth/login
func (UnimplementedHandler) AuthLogin(ctx context.Context, req *AuthLoginRequest) (r AuthLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthLogout implements authLogout operation.
//
// 登出（递增 token_version 使所有 token 失效）.
//
// POST /api/auth/logout
func (UnimplementedHandler) AuthLogout(ctx context.Context) (r AuthLogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthRefresh implements authRefresh operation.
//
// 用 refresh token 换 access token.
//
// POST /api/auth/refresh
func (UnimplementedHandler) AuthRefresh(ctx context.Context, req *AuthRefreshRequest) (r AuthRefreshRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CustomersCreate implements customersCreate operation.
//
// 创建客户.
//
// POST /api/customers
func (UnimplementedHandler) CustomersCreate(ctx context.Context, req *CustomerCreateRequest) (r CustomersCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CustomersGet implements customersGet operation.
//
// GET /api/customers/{id}
func (UnimplementedHandler) CustomersGet(ctx context.Context, params CustomersGetParams) (r CustomersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CustomersList implements customersList operation.
//
// 列出客户（按权限过滤）.
//
// GET /api/customers
func (UnimplementedHandler) CustomersList(ctx context.Context) (r CustomersListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CustomersUpdate implements customersUpdate operation.
//
// PATCH /api/customers/{id}
func (UnimplementedHandler) CustomersUpdate(ctx context.Context, req *CustomerUpdateRequest, params CustomersUpdateParams) (r CustomersUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FeedbacksUpdate implements feedbacksUpdate operation.
//
// 修改反馈状态（pending → done）.
//
// PATCH /api/feedbacks/{id}
func (UnimplementedHandler) FeedbacksUpdate(ctx context.Context, req *FeedbackUpdateRequest, params FeedbacksUpdateParams) (r FeedbacksUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FilesDownload implements filesDownload operation.
//
// 下载文件（流式）.
//
// GET /api/files/{id}
func (UnimplementedHandler) FilesDownload(ctx context.Context, params FilesDownloadParams) (r FilesDownloadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FilesUpload implements filesUpload operation.
//
// 上传文件，返回文件元数据.
//
// POST /api/files
func (UnimplementedHandler) FilesUpload(ctx context.Context, req *FilesUploadReq) (r FilesUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MeEarnings implements meEarnings operation.
//
// 当前用户收益视图（自动按 user_id 过滤）.
//
// GET /api/me/earnings
func (UnimplementedHandler) MeEarnings(ctx context.Context) (r *EarningsSummaryResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NotificationsList implements notificationsList operation.
//
// 当前用户通知.
//
// GET /api/notifications
func (UnimplementedHandler) NotificationsList(ctx context.Context, params NotificationsListParams) (r *NotificationListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NotificationsMarkAllRead implements notificationsMarkAllRead operation.
//
// 全部标为已读.
//
// POST /api/notifications/read-all
func (UnimplementedHandler) NotificationsMarkAllRead(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// NotificationsMarkRead implements notificationsMarkRead operation.
//
// 标记单条通知为已读.
//
// POST /api/notifications/{id}/read
func (UnimplementedHandler) NotificationsMarkRead(ctx context.Context, params NotificationsMarkReadParams) (r NotificationsMarkReadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PermissionsList implements permissionsList operation.
//
// 列出所有权限.
//
// GET /api/permissions
func (UnimplementedHandler) PermissionsList(ctx context.Context) (r PermissionsListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsCreate implements projectsCreate operation.
//
// 创建项目（默认进入 dealing 状态）.
//
// POST /api/projects
func (UnimplementedHandler) ProjectsCreate(ctx context.Context, req *ProjectCreateRequest) (r ProjectsCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsCreateFeedback implements projectsCreateFeedback operation.
//
// POST /api/projects/{id}/feedbacks
func (UnimplementedHandler) ProjectsCreateFeedback(ctx context.Context, req *FeedbackCreateRequest, params ProjectsCreateFeedbackParams) (r ProjectsCreateFeedbackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsCreatePayment implements projectsCreatePayment operation.
//
// 录入收款或开发结算.
//
// POST /api/projects/{id}/payments
func (UnimplementedHandler) ProjectsCreatePayment(ctx context.Context, req *PaymentCreateRequest, params ProjectsCreatePaymentParams) (r ProjectsCreatePaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsCreateQuoteChange implements projectsCreateQuoteChange operation.
//
// 提交费用变更（追加 / 修改 / 售后）.
//
// POST /api/projects/{id}/quote-changes
func (UnimplementedHandler) ProjectsCreateQuoteChange(ctx context.Context, req *QuoteChangeRequest, params ProjectsCreateQuoteChangeParams) (r ProjectsCreateQuoteChangeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsCreateThesisVersion implements projectsCreateThesisVersion operation.
//
// 上传论文新版（永不覆盖，version_no 自动递增）.
//
// POST /api/projects/{id}/thesis-versions
func (UnimplementedHandler) ProjectsCreateThesisVersion(ctx context.Context, req *ThesisVersionCreateRequest, params ProjectsCreateThesisVersionParams) (r ProjectsCreateThesisVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsGet implements projectsGet operation.
//
// GET /api/projects/{id}
func (UnimplementedHandler) ProjectsGet(ctx context.Context, params ProjectsGetParams) (r ProjectsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsList implements projectsList operation.
//
// 列出项目（按 RBAC 过滤）.
//
// GET /api/projects
func (UnimplementedHandler) ProjectsList(ctx context.Context, params ProjectsListParams) (r ProjectsListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsListFeedbacks implements projectsListFeedbacks operation.
//
// GET /api/projects/{id}/feedbacks
func (UnimplementedHandler) ProjectsListFeedbacks(ctx context.Context, params ProjectsListFeedbacksParams) (r *FeedbackListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsListFiles implements projectsListFiles operation.
//
// 列出项目附件（sample_doc / source_code）.
//
// GET /api/projects/{id}/files
func (UnimplementedHandler) ProjectsListFiles(ctx context.Context, params ProjectsListFilesParams) (r *ProjectFileListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsListPayments implements projectsListPayments operation.
//
// GET /api/projects/{id}/payments
func (UnimplementedHandler) ProjectsListPayments(ctx context.Context, params ProjectsListPaymentsParams) (r *PaymentListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsListQuoteChanges implements projectsListQuoteChanges operation.
//
// GET /api/projects/{id}/quote-changes
func (UnimplementedHandler) ProjectsListQuoteChanges(ctx context.Context, params ProjectsListQuoteChangesParams) (r *QuoteChangeListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsListThesisVersions implements projectsListThesisVersions operation.
//
// GET /api/projects/{id}/thesis-versions
func (UnimplementedHandler) ProjectsListThesisVersions(ctx context.Context, params ProjectsListThesisVersionsParams) (r *ThesisVersionListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsStatusChanges implements projectsStatusChanges operation.
//
// 查询项目状态变更日志.
//
// GET /api/projects/{id}/status-changes
func (UnimplementedHandler) ProjectsStatusChanges(ctx context.Context, params ProjectsStatusChangesParams) (r ProjectsStatusChangesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsTriggerEvent implements projectsTriggerEvent operation.
//
// 触发状态机事件.
//
// POST /api/projects/{id}/events
func (UnimplementedHandler) ProjectsTriggerEvent(ctx context.Context, req *EventTriggerRequest, params ProjectsTriggerEventParams) (r ProjectsTriggerEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProjectsUpdate implements projectsUpdate operation.
//
// 修改项目基础字段（不含状态机）.
//
// PATCH /api/projects/{id}
func (UnimplementedHandler) ProjectsUpdate(ctx context.Context, req *ProjectUpdateRequest, params ProjectsUpdateParams) (r ProjectsUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RolesList implements rolesList operation.
//
// 列出所有角色.
//
// GET /api/roles
func (UnimplementedHandler) RolesList(ctx context.Context) (r RolesListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersList implements usersList operation.
//
// 列出所有用户（仅超管）.
//
// GET /api/users
func (UnimplementedHandler) UsersList(ctx context.Context) (r UsersListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersMe implements usersMe operation.
//
// 获取当前登录用户.
//
// GET /api/users/me
func (UnimplementedHandler) UsersMe(ctx context.Context) (r UsersMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WsNotificationsConnect implements wsNotificationsConnect operation.
//
// WebSocket 升级端点（非 HTTP REST，仅 OpenAPI 描述）。
// 协议：客户端 query 参数携带 ticket，服务端校验 ticket 后升级；
// 消息帧 JSON：{ "type": "notification.new" | "ping" | "pong", "data": <payload> }。
// ogen 不会为此生成 handler，由 router.go 直接注册 ws 处理器。.
//
// GET /api/ws/notifications
func (UnimplementedHandler) WsNotificationsConnect(ctx context.Context, params WsNotificationsConnectParams) (r WsNotificationsConnectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// WsTicketIssue implements wsTicketIssue operation.
//
// 签发 WebSocket 票据（30s 有效）.
//
// POST /api/ws/ticket
func (UnimplementedHandler) WsTicketIssue(ctx context.Context) (r *WSTicketResponse, _ error) {
	return r, ht.ErrNotImplemented
}
