// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginOperation                   OperationName = "AuthLogin"
	AuthLogoutOperation                  OperationName = "AuthLogout"
	AuthRefreshOperation                 OperationName = "AuthRefresh"
	CustomersCreateOperation             OperationName = "CustomersCreate"
	CustomersGetOperation                OperationName = "CustomersGet"
	CustomersListOperation               OperationName = "CustomersList"
	CustomersUpdateOperation             OperationName = "CustomersUpdate"
	FeedbacksUpdateOperation             OperationName = "FeedbacksUpdate"
	FilesDownloadOperation               OperationName = "FilesDownload"
	FilesUploadOperation                 OperationName = "FilesUpload"
	MeEarningsOperation                  OperationName = "MeEarnings"
	NotificationsListOperation           OperationName = "NotificationsList"
	NotificationsMarkAllReadOperation    OperationName = "NotificationsMarkAllRead"
	NotificationsMarkReadOperation       OperationName = "NotificationsMarkRead"
	PermissionsListOperation             OperationName = "PermissionsList"
	ProjectsCreateOperation              OperationName = "ProjectsCreate"
	ProjectsCreateFeedbackOperation      OperationName = "ProjectsCreateFeedback"
	ProjectsCreatePaymentOperation       OperationName = "ProjectsCreatePayment"
	ProjectsCreateQuoteChangeOperation   OperationName = "ProjectsCreateQuoteChange"
	ProjectsCreateThesisVersionOperation OperationName = "ProjectsCreateThesisVersion"
	ProjectsGetOperation                 OperationName = "ProjectsGet"
	ProjectsListOperation                OperationName = "ProjectsList"
	ProjectsListFeedbacksOperation       OperationName = "ProjectsListFeedbacks"
	ProjectsListFilesOperation           OperationName = "ProjectsListFiles"
	ProjectsListPaymentsOperation        OperationName = "ProjectsListPayments"
	ProjectsListQuoteChangesOperation    OperationName = "ProjectsListQuoteChanges"
	ProjectsListThesisVersionsOperation  OperationName = "ProjectsListThesisVersions"
	ProjectsStatusChangesOperation       OperationName = "ProjectsStatusChanges"
	ProjectsTriggerEventOperation        OperationName = "ProjectsTriggerEvent"
	ProjectsUpdateOperation              OperationName = "ProjectsUpdate"
	RolesListOperation                   OperationName = "RolesList"
	UsersListOperation                   OperationName = "UsersList"
	UsersMeOperation                     OperationName = "UsersMe"
	WsNotificationsConnectOperation      OperationName = "WsNotificationsConnect"
	WsTicketIssueOperation               OperationName = "WsTicketIssue"
)
