/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录获取 access + refresh token */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用 refresh token 换 access token */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（递增 token_version 使所有 token 失效） */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前登录用户 */
        get: operations["authGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有用户（仅超管） */
        get: operations["usersList"];
        put?: never;
        /** 创建用户（仅超管） */
        post: operations["usersCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户（仅超管，软删除：置 isActive=false 并失效 token_version） */
        delete: operations["usersDelete"];
        options?: never;
        head?: never;
        /** 修改用户（仅超管） */
        patch: operations["usersUpdate"];
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有角色 */
        get: operations["rolesList"];
        put?: never;
        /** 创建角色（仅超管） */
        post: operations["rolesCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** 查询某角色绑定的权限列表 */
        get: operations["rolesGetPermissions"];
        /** 全量替换角色的权限绑定（仅超管；super_admin role 由中间件 422 拦截） */
        put: operations["rolesUpdatePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有权限 */
        get: operations["permissionsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/effective-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前登录用户的有效权限码列表（已合并 role grants + user grant - user deny） */
        get: operations["meGetEffectivePermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/permission-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** 查询某用户当前的权限覆写（grant/deny）；仅超管可调 */
        get: operations["usersGetPermissionOverrides"];
        /** 全量替换某用户的权限覆写；超管目标由中间件 422 拦截 */
        put: operations["usersUpdatePermissionOverrides"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出项目（按 RBAC 过滤） */
        get: operations["projectsList"];
        put?: never;
        /** 创建项目（默认进入 dealing 状态） */
        post: operations["projectsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["projectsGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改项目基础字段（不含状态机） */
        patch: operations["projectsUpdate"];
        trace?: never;
    };
    "/api/projects/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发状态机事件 */
        post: operations["projectsTriggerEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/status-changes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** 查询项目状态变更日志 */
        get: operations["projectsStatusChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** 查询项目进度时间线（聚合 7 类事件，时间倒序） */
        get: operations["projectsListActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["projectsListFeedbacks"];
        put?: never;
        post: operations["projectsCreateFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedbacks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改反馈状态（pending → done） */
        patch: operations["feedbacksUpdate"];
        trace?: never;
    };
    "/api/projects/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["projectsListPayments"];
        put?: never;
        /** 录入收款或开发结算 */
        post: operations["projectsCreatePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** 列出项目附件（sample_doc / source_code） */
        get: operations["projectsListFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/quote-changes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["projectsListQuoteChanges"];
        put?: never;
        /** 提交费用变更（追加 / 修改 / 售后） */
        post: operations["projectsCreateQuoteChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/thesis-versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["projectsListThesisVersions"];
        put?: never;
        /** 上传论文新版（永不覆盖，version_no 自动递增） */
        post: operations["projectsCreateThesisVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传文件，返回文件元数据 */
        post: operations["filesUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** 下载文件（流式） */
        get: operations["filesDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户通知 */
        get: operations["notificationsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 标记单条通知为已读 */
        post: operations["notificationsMarkRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 全部标为已读 */
        post: operations["notificationsMarkAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户收益视图（自动按 user_id 过滤） */
        get: operations["meEarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 风险总览（临近 deadline / 已超期 / 应收逾期），按 RBAC 过滤 */
        get: operations["dashboardGetRisks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws/ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 签发 WebSocket 票据（30s 有效） */
        post: operations["wsTicketIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket 升级端点（非 HTTP REST，仅 OpenAPI 描述）。
         *     协议：客户端 query 参数携带 ticket，服务端校验 ticket 后升级；
         *     消息帧 JSON：{ "type": "notification.new" | "ping" | "pong", "data": <payload> }。
         *     ogen 不会为此生成 handler，由 router.go 直接注册 ws 处理器。
         */
        get: operations["wsNotificationsConnect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "unauthorized" | "permission_denied" | "not_found" | "validation_failed" | "state_machine_invalid_transition" | "mime_not_allowed" | "file_too_large" | "ticket_invalid" | "not_implemented" | "internal" | "super_admin_immutable" | "request_body_too_large" | "service_unavailable" | "invalid_effect" | "permission_not_found";
                message: string;
                details?: {
                    [key: string]: unknown;
                } | null;
            };
        };
        /** @description 十进制金额，最多 12 位整数 + 2 位小数（与 Postgres NUMERIC(12,2) 对齐，前端用 decimal.js 处理） */
        Money: string;
        User: {
            /** Format: int64 */
            id: number;
            /** @description 登录用 username（唯一） */
            username: string;
            displayName: string;
            /** Format: int64 */
            roleId: number;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** @description 当前 session 持有的权限码集合（仅在 /api/auth/me 响应中填充，登录/创建用户响应留空）。元素形如 'project:read'、'event:E10'。 */
            permissions?: string[];
        };
        UserCreateRequest: {
            /** @description 登录用 username（唯一） */
            username: string;
            /** @description 明文密码，服务端 bcrypt 后入库 */
            password: string;
            /** @description 可选展示名，缺省取 username */
            displayName?: string;
            /** Format: int64 */
            roleId: number;
        };
        /** @description PATCH 部分字段，所有字段 optional；密码字段独立显式传以便审计 */
        UserUpdateRequest: {
            username?: string;
            password?: string;
            displayName?: string;
            /** Format: int64 */
            roleId?: number;
            isActive?: boolean;
        };
        Role: {
            /** Format: int64 */
            id: number;
            name: string;
            description?: string | null;
            isSystem: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        RoleCreateRequest: {
            name: string;
            description?: string;
            /** @description 可选：创建时一并绑定的权限 id 列表 */
            permissionIds?: number[];
        };
        RolePermissionUpdateRequest: {
            /** @description 目标权限 id 全集；服务端做差集替换 */
            permissionIds: number[];
        };
        Permission: {
            /** Format: int64 */
            id: number;
            /** @description 资源命名空间，如 nav / progress / users / permissions */
            resource: string;
            /** @description 动作，如 view / list / create / edit / delete / role / user_override */
            action: string;
            /** @description 范围，如 work / progress / atlas / all / manage */
            scope: string;
            /** @description 三段式权限码 resource:action:scope（前端 PermissionGate 直接消费） */
            code: string;
        };
        /** @description user 级权限覆写：grant 强行追加；deny 强行扣除（超管不允许任何 override） */
        UserPermissionOverride: {
            /** Format: int64 */
            permissionId: number;
            /** @enum {string} */
            effect: "grant" | "deny";
        };
        UserPermissionOverridesResponse: {
            /** Format: int64 */
            userId: number;
            overrides: components["schemas"]["UserPermissionOverride"][];
        };
        UpdateUserPermissionOverridesRequest: {
            overrides: components["schemas"]["UserPermissionOverride"][];
        };
        EffectivePermissionsResponse: {
            /** @description 已计算合并的权限码列表（resource:action:scope）；超管时为单元素 ['*:*'] */
            permissions: string[];
            /** @description true 表示当前用户是 super_admin；前端可据此跳过任何权限门控 */
            superAdmin: boolean;
        };
        /** @enum {string} */
        ProjectStatus: "dealing" | "quoting" | "developing" | "confirming" | "delivered" | "paid" | "archived" | "after_sales" | "cancelled";
        /** @enum {string} */
        ProjectPriority: "urgent" | "normal";
        /** @enum {string} */
        ThesisLevel: "bachelor" | "master" | "doctor";
        Project: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description 客户标签（自由文本，例如 '张三 / 张三@wx'），由用户自由填写 */
            customerLabel: string;
            description: string;
            priority: components["schemas"]["ProjectPriority"];
            thesisLevel?: components["schemas"]["ThesisLevel"] | null;
            subject?: string | null;
            status: components["schemas"]["ProjectStatus"];
            /** Format: int64 */
            holderRoleId?: number | null;
            /** Format: int64 */
            holderUserId?: number | null;
            /** Format: date-time */
            deadline: string;
            /** Format: date-time */
            dealingAt: string;
            /** Format: date-time */
            quotingAt?: string | null;
            /** Format: date-time */
            devStartedAt?: string | null;
            /** Format: date-time */
            confirmingAt?: string | null;
            /** Format: date-time */
            deliveredAt?: string | null;
            /** Format: date-time */
            paidAt?: string | null;
            /** Format: date-time */
            archivedAt?: string | null;
            /** Format: date-time */
            afterSalesAt?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
            originalQuote: components["schemas"]["Money"];
            currentQuote: components["schemas"]["Money"];
            afterSalesTotal: components["schemas"]["Money"];
            totalReceived: components["schemas"]["Money"];
            /** Format: int64 */
            openingDocId?: number | null;
            /** Format: int64 */
            assignmentDocId?: number | null;
            /** Format: int64 */
            formatSpecDocId?: number | null;
            /** Format: int64 */
            createdBy: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectCreateRequest: {
            name: string;
            /** @description 客户标签（自由文本） */
            customerLabel: string;
            description: string;
            priority?: components["schemas"]["ProjectPriority"];
            thesisLevel?: components["schemas"]["ThesisLevel"];
            subject?: string;
            /** Format: date-time */
            deadline: string;
            originalQuote?: components["schemas"]["Money"];
            /**
             * Format: int64
             * @description 开题书文件 ID（先 POST /api/files 上传得 fileId，再带入此字段）
             */
            openingDocId?: number | null;
            /**
             * Format: int64
             * @description 任务书文件 ID（先 POST /api/files 上传得 fileId，再带入此字段）
             */
            assignmentDocId?: number | null;
            /** @description 微信聊天记录截图文件 ID 数组（多张图先逐个上传，再带 ID 数组；后端事务 INSERT project_files category=wechat_chat） */
            wechatChatFileIds?: number[];
        };
        /** @description PATCH 部分字段，全部 optional */
        ProjectUpdateRequest: {
            name?: string;
            /** @description 客户标签（自由文本），允许 cs/admin 修改 */
            customerLabel?: string;
            description?: string;
            priority?: components["schemas"]["ProjectPriority"];
            thesisLevel?: components["schemas"]["ThesisLevel"];
            subject?: string | null;
            /** Format: date-time */
            deadline?: string;
        };
        /**
         * @description 状态机事件代码，详见 spec §6.2
         * @enum {string}
         */
        EventCode: "E0" | "E1" | "E2" | "E3" | "E4" | "E5" | "E6" | "E7" | "E8" | "E9" | "E10" | "E11" | "E12" | "E13" | "E_AS1" | "E_AS3";
        EventTriggerRequest: {
            event: components["schemas"]["EventCode"];
            /** @description 状态变更日志必填备注 */
            remark: string;
            /**
             * Format: int64
             * @description 事件需要换持球者时填写（如 E2 由超管指定开发者）
             */
            newHolderUserId?: number | null;
        };
        StatusChangeLog: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            projectId: number;
            eventCode: string;
            eventName: string;
            fromStatus?: components["schemas"]["ProjectStatus"] | null;
            toStatus: components["schemas"]["ProjectStatus"];
            /** Format: int64 */
            fromHolderId?: number | null;
            /** Format: int64 */
            toHolderId?: number | null;
            remark: string;
            /** Format: int64 */
            triggeredBy: number;
            /** Format: date-time */
            triggeredAt: string;
        };
        /** @enum {string} */
        FeedbackSource: "phone" | "wechat" | "email" | "meeting" | "other";
        /** @enum {string} */
        FeedbackStatus: "pending" | "done";
        Feedback: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            projectId: number;
            content: string;
            source: components["schemas"]["FeedbackSource"];
            status: components["schemas"]["FeedbackStatus"];
            /** Format: int64 */
            recordedBy: number;
            /** Format: date-time */
            recordedAt: string;
            attachmentIds?: number[];
        };
        FeedbackCreateRequest: {
            content: string;
            source?: components["schemas"]["FeedbackSource"];
            attachmentIds?: number[];
        };
        FeedbackUpdateRequest: {
            status?: components["schemas"]["FeedbackStatus"];
        };
        /** @enum {string} */
        PaymentDirection: "customer_in" | "dev_settlement";
        Payment: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            projectId: number;
            direction: components["schemas"]["PaymentDirection"];
            amount: components["schemas"]["Money"];
            /** Format: date-time */
            paidAt: string;
            /**
             * Format: int64
             * @description 仅 dev_settlement 必填
             */
            relatedUserId?: number | null;
            /**
             * Format: int64
             * @description 仅 dev_settlement 必填（截图 file_id）
             */
            screenshotId?: number | null;
            remark: string;
            /** Format: int64 */
            recordedBy: number;
            /** Format: date-time */
            recordedAt: string;
        };
        PaymentCreateRequest: {
            direction: components["schemas"]["PaymentDirection"];
            amount: components["schemas"]["Money"];
            /** Format: date-time */
            paidAt: string;
            /** Format: int64 */
            relatedUserId?: number | null;
            /** Format: int64 */
            screenshotId?: number | null;
            remark: string;
        };
        FileMetadata: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            uuid: string;
            filename: string;
            /** Format: int64 */
            sizeBytes: number;
            mimeType: string;
            /** Format: int64 */
            uploadedBy: number;
            /** Format: date-time */
            uploadedAt: string;
        };
        ProjectFile: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            projectId: number;
            /** Format: int64 */
            fileId: number;
            /** @enum {string} */
            category: "sample_doc" | "source_code" | "wechat_chat";
            /** Format: date-time */
            addedAt: string;
            file: components["schemas"]["FileMetadata"];
        };
        ThesisVersion: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            projectId: number;
            /** Format: int64 */
            fileId: number;
            versionNo: number;
            remark?: string | null;
            /** Format: int64 */
            uploadedBy: number;
            /** Format: date-time */
            uploadedAt: string;
            file: components["schemas"]["FileMetadata"];
        };
        ThesisVersionCreateRequest: {
            /** Format: int64 */
            fileId: number;
            remark?: string;
        };
        /** @enum {string} */
        QuoteChangeType: "append" | "modify" | "after_sales";
        QuoteChange: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            projectId: number;
            changeType: components["schemas"]["QuoteChangeType"];
            delta: components["schemas"]["Money"];
            oldQuote: components["schemas"]["Money"];
            newQuote: components["schemas"]["Money"];
            reason: string;
            phase: components["schemas"]["ProjectStatus"];
            /** Format: int64 */
            changedBy: number;
            /** Format: date-time */
            changedAt: string;
        };
        QuoteChangeRequest: {
            changeType: components["schemas"]["QuoteChangeType"];
            delta?: components["schemas"]["Money"];
            newQuote?: components["schemas"]["Money"];
            reason: string;
        };
        /** @enum {string} */
        NotificationType: "ball_passed" | "deadline_approaching" | "overdue" | "new_feedback" | "settlement_received" | "project_terminated";
        Notification: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            userId: number;
            type: components["schemas"]["NotificationType"];
            /** Format: int64 */
            projectId?: number | null;
            title: string;
            body: string;
            isRead: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readAt?: string | null;
        };
        EarningsSummary: {
            /** Format: int64 */
            userId: number;
            totalEarned: components["schemas"]["Money"];
            settlementCount: number;
            /** Format: date-time */
            lastPaidAt?: string | null;
            projects: {
                /** Format: int64 */
                projectId: number;
                projectName: string;
                totalEarned: components["schemas"]["Money"];
                settlementCount: number;
                /** Format: date-time */
                lastPaidAt?: string | null;
            }[];
        };
        /**
         * @description 风险类型：临近 deadline / 已超期 / 应收逾期
         * @enum {string}
         */
        RiskType: "deadline_warning" | "overdue" | "payment_overdue";
        /**
         * @description 风险严重度，前端用于颜色/排序
         * @enum {string}
         */
        RiskSeverity: "warning" | "critical";
        RiskItem: {
            /** Format: int64 */
            projectId: number;
            /** @description 客户标签（来自 projects.customer_label） */
            customerLabel: string;
            riskType: components["schemas"]["RiskType"];
            /**
             * Format: date-time
             * @description 对 deadline_warning/overdue 是 deadline；对 payment_overdue 是预计收款日
             */
            dueAt: string;
            severity: components["schemas"]["RiskSeverity"];
        };
        AuthLoginRequest: {
            /** @description 登录用 username */
            username: string;
            password: string;
        };
        AuthLoginResponse: {
            /** @description 短期 access token (15min) */
            accessToken: string;
            /** @description 长期 refresh token (30d) */
            refreshToken: string;
            user: components["schemas"]["User"];
        };
        AuthRefreshRequest: {
            refreshToken: string;
        };
        AuthRefreshResponse: {
            /** @description 新签发的 access token */
            accessToken: string;
            /** @description rotate 后的新 refresh token，client 必须写回 localStorage 替换旧值（旧值已在 DB revoked） */
            refreshToken: string;
        };
        WSTicket: {
            /** @description 短期 WS 票据，用于建立 /ws/notifications 连接 */
            ticket: string;
            /**
             * Format: date-time
             * @description 票据过期时间（一般 30s）
             */
            expiresAt: string;
        };
        UserResponse: {
            data: components["schemas"]["User"];
        };
        UserListResponse: {
            data: components["schemas"]["User"][];
        };
        RoleListResponse: {
            data: components["schemas"]["Role"][];
        };
        PermissionListResponse: {
            data: components["schemas"]["Permission"][];
        };
        ProjectResponse: {
            data: components["schemas"]["Project"];
        };
        ProjectListResponse: {
            data: components["schemas"]["Project"][];
        };
        StatusChangeLogListResponse: {
            data: components["schemas"]["StatusChangeLog"][];
        };
        FeedbackResponse: {
            data: components["schemas"]["Feedback"];
        };
        FeedbackListResponse: {
            data: components["schemas"]["Feedback"][];
        };
        PaymentResponse: {
            data: components["schemas"]["Payment"];
        };
        PaymentListResponse: {
            data: components["schemas"]["Payment"][];
        };
        ProjectFileListResponse: {
            data: components["schemas"]["ProjectFile"][];
        };
        FileMetadataResponse: {
            data: components["schemas"]["FileMetadata"];
        };
        ThesisVersionResponse: {
            data: components["schemas"]["ThesisVersion"];
        };
        ThesisVersionListResponse: {
            data: components["schemas"]["ThesisVersion"][];
        };
        QuoteChangeResponse: {
            data: components["schemas"]["QuoteChange"];
        };
        QuoteChangeListResponse: {
            data: components["schemas"]["QuoteChange"][];
        };
        NotificationListResponse: {
            data: components["schemas"]["Notification"][];
        };
        EarningsSummaryResponse: {
            data: components["schemas"]["EarningsSummary"];
        };
        RoleResponse: {
            data: components["schemas"]["Role"];
        };
        RiskListResponse: {
            data: components["schemas"]["RiskItem"][];
        };
        AuthLoginEnvelope: {
            data: components["schemas"]["AuthLoginResponse"];
        };
        AuthRefreshEnvelope: {
            data: components["schemas"]["AuthRefreshResponse"];
        };
        WSTicketResponse: {
            data: components["schemas"]["WSTicket"];
        };
        /** @enum {string} */
        ActivityKind: "project_created" | "feedback" | "status_change" | "quote_change" | "payment" | "thesis_version" | "project_file_added";
        Activity: {
            /** @description 稳定展示 id（kind:sourceId） */
            id: string;
            /** Format: int64 */
            sourceId: number;
            /** Format: int64 */
            projectId: number;
            kind: components["schemas"]["ActivityKind"];
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            actorId: number;
            actorName?: string | null;
            actorRoleName?: string | null;
            payload: components["schemas"]["ProjectCreatedPayload"] | components["schemas"]["FeedbackActivityPayload"] | components["schemas"]["StatusChangeActivityPayload"] | components["schemas"]["QuoteChangeActivityPayload"] | components["schemas"]["PaymentActivityPayload"] | components["schemas"]["ThesisVersionActivityPayload"] | components["schemas"]["ProjectFileAddedPayload"];
        };
        ActivityListResponse: {
            data: components["schemas"]["Activity"][];
            nextCursor?: string | null;
        };
        ProjectCreatedPayload: {
            name: string;
            status: components["schemas"]["ProjectStatus"];
            priority: components["schemas"]["ProjectPriority"];
            /** Format: date-time */
            deadline: string;
            originalQuote: components["schemas"]["Money"];
        };
        FeedbackActivityPayload: {
            content: string;
            source: components["schemas"]["FeedbackSource"];
            status: components["schemas"]["FeedbackStatus"];
        };
        StatusChangeActivityPayload: {
            eventCode: string;
            eventName: string;
            fromStatus?: components["schemas"]["ProjectStatus"] | null;
            toStatus: components["schemas"]["ProjectStatus"];
            /** Format: int64 */
            fromHolderRoleId?: number | null;
            /** Format: int64 */
            toHolderRoleId?: number | null;
            /** Format: int64 */
            fromHolderUserId?: number | null;
            /** Format: int64 */
            toHolderUserId?: number | null;
            remark: string;
        };
        QuoteChangeActivityPayload: {
            changeType: components["schemas"]["QuoteChangeType"];
            delta: components["schemas"]["Money"];
            oldQuote: components["schemas"]["Money"];
            newQuote: components["schemas"]["Money"];
            reason: string;
            phase: components["schemas"]["ProjectStatus"];
        };
        PaymentActivityPayload: {
            direction: components["schemas"]["PaymentDirection"];
            amount: components["schemas"]["Money"];
            /** Format: date-time */
            paidAt: string;
            /** Format: int64 */
            relatedUserId?: number | null;
            /** Format: int64 */
            screenshotId?: number | null;
            remark: string;
        };
        ThesisVersionActivityPayload: {
            /** Format: int64 */
            fileId: number;
            versionNo: number;
            remark?: string | null;
        };
        ProjectFileAddedPayload: {
            /** Format: int64 */
            fileId: number;
            /** @enum {string} */
            category: "sample_doc" | "source_code";
        };
    };
    responses: {
        /** @description 缺失或无效凭证 */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 无权限 */
        PermissionDeniedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 资源不存在 */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 请求体校验失败 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 接口尚未实现（Phase 0a skeleton 阶段） */
        NotImplementedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginEnvelope"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            422: components["responses"]["ValidationError"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description 刷新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRefreshEnvelope"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    authGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    usersList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
        };
    };
    usersCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
            422: components["responses"]["ValidationError"];
        };
    };
    usersDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    usersUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["ValidationError"];
        };
    };
    rolesList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    rolesCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
            422: components["responses"]["ValidationError"];
        };
    };
    rolesGetPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    rolesUpdatePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolePermissionUpdateRequest"];
            };
        };
        responses: {
            /** @description 已替换 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["ValidationError"];
        };
    };
    permissionsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    meGetEffectivePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectivePermissionsResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    usersGetPermissionOverrides: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPermissionOverridesResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    usersUpdatePermissionOverrides: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserPermissionOverridesRequest"];
            };
        };
        responses: {
            /** @description 已替换 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["ValidationError"];
        };
    };
    projectsList: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProjectStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    projectsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            422: components["responses"]["ValidationError"];
        };
    };
    projectsGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    projectsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["ValidationError"];
        };
    };
    projectsTriggerEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTriggerRequest"];
            };
        };
        responses: {
            /** @description 事件已触发，返回最新项目 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description 状态机不允许此跳转 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    projectsStatusChanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChangeLogListResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    projectsListActivities: {
        parameters: {
            query?: {
                limit?: number;
                /** @description base64url JSON 游标（at, kind, sourceId 三元组） */
                before?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进度时间线分页数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["PermissionDeniedError"];
            404: components["responses"]["NotFoundError"];
            /** @description 游标非法 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    projectsListFeedbacks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackListResponse"];
                };
            };
        };
    };
    projectsCreateFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    feedbacksUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    projectsListPayments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentListResponse"];
                };
            };
        };
    };
    projectsCreatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    projectsListFiles: {
        parameters: {
            query?: {
                category?: "sample_doc" | "source_code";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileListResponse"];
                };
            };
        };
    };
    projectsListQuoteChanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteChangeListResponse"];
                };
            };
        };
    };
    projectsCreateQuoteChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteChangeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteChangeResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    projectsListThesisVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisVersionListResponse"];
                };
            };
        };
    };
    projectsCreateThesisVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThesisVersionCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisVersionResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    filesUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 文件已上传 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetadataResponse"];
                };
            };
            /** @description 文件过大 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description MIME 不允许 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    filesDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文件内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    notificationsList: {
        parameters: {
            query?: {
                unreadOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
        };
    };
    notificationsMarkRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已标记 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    notificationsMarkAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已标记 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    meEarnings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarningsSummaryResponse"];
                };
            };
        };
    };
    dashboardGetRisks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    wsTicketIssue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 票据已签发 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WSTicketResponse"];
                };
            };
        };
    };
    wsNotificationsConnect: {
        parameters: {
            query: {
                ticket: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
}
